/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author Alison
 */
public class frmMain extends javax.swing.JFrame {
        Hilo hilo1 = new Hilo();
        Hilo hilo2 = new Hilo();
        Hilo hilo3 = new Hilo();
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        
        initComponents();
        hilo1.window = 1;
        hilo2.window = 2;
        hilo3.window = 3;
        hilo1.start();
        hilo2.start();
        hilo3.start();
        Border border = BorderFactory.createLineBorder(Color.BLACK, 3);
        jLabel2.setText("");
        jLabel2.setBorder(border);
        Image img = new ImageIcon(this.getClass().getResource("/Imagenes/img1.jpg")).getImage();
        img = img.getScaledInstance(315, 400, java.awt.Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(img));
        
        //
        
        jLabel3.setText("");
        jLabel3.setBorder(border);
        img = new ImageIcon(this.getClass().getResource("/Imagenes/img2.jpg")).getImage();
        img = img.getScaledInstance(315, 400, java.awt.Image.SCALE_SMOOTH);
        jLabel3.setIcon(new ImageIcon(img));
        
        //
        
        jLabel4.setText("");
        jLabel4.setBorder(border);
        img = new ImageIcon(this.getClass().getResource("/Imagenes/img3.jpg")).getImage();
        img = img.getScaledInstance(315, 400, java.awt.Image.SCALE_SMOOTH);
        jLabel4.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        Dtn1 = new javax.swing.JButton();
        Dtn2 = new javax.swing.JButton();
        Dtn3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1250, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Casino");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("?");

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        Dtn1.setText("Detener 1");
        Dtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dtn1ActionPerformed(evt);
            }
        });

        Dtn2.setText("Detener 2");
        Dtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dtn2ActionPerformed(evt);
            }
        });

        Dtn3.setText("Detener 3");
        Dtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dtn3ActionPerformed(evt);
            }
        });

        jButton1.setText("Detener todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(Dtn1)
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Iniciar)
                                .addGap(25, 25, 25)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dtn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(Dtn3)
                        .addGap(196, 196, 196))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dtn1)
                    .addComponent(Dtn2)
                    .addComponent(Dtn3))
                .addGap(94, 94, 94)
                .addComponent(Iniciar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        hilo1.starRunning();
        hilo2.starRunning();
        hilo3.starRunning();
    }//GEN-LAST:event_IniciarActionPerformed

    private void Dtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dtn1ActionPerformed
        // TODO add your handling code here:
        hilo1.stopRunning();    
    }//GEN-LAST:event_Dtn1ActionPerformed

    private void Dtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dtn2ActionPerformed
        // TODO add your handling code here:
        hilo2.stopRunning();    
    }//GEN-LAST:event_Dtn2ActionPerformed

    private void Dtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dtn3ActionPerformed
        // TODO add your handling code here:
        hilo3.stopRunning();
    }//GEN-LAST:event_Dtn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hilo1.stopRunning();
        hilo2.stopRunning();
        hilo3.stopRunning();
        if(jLabel1.getIcon() == jLabel2.getIcon() && jLabel1.getIcon() == jLabel3.getIcon()){
            JOptionPane.showMessageDialog(null, "Has ganado");
        }else{
            JOptionPane.showMessageDialog(null, "Intentalo de nuevo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dtn1;
    private javax.swing.JButton Dtn2;
    private javax.swing.JButton Dtn3;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private class Hilo extends Thread {
        public int window = 0;
        private boolean run = false;
        
        public void starRunning(){
            run = true;
        }
        
        public void stopRunning(){
            run = false;
        }
        
        public int getRandom(){
            int random = (int)(Math.random() * 3 + 1);
            return random;
        }
        
        public void run(){
            Image img;
            while(window == 1){
                while(run){
                    if(this.getRandom() == 1){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img1.jpg")).getImage();
                    }else if (this.getRandom() == 2){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img2.jpg")).getImage();
                    }else{
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img3.jpg")).getImage();
                    }
                    img = img.getScaledInstance(315, 400, java.awt.Image.SCALE_SMOOTH);
                    jLabel2.setIcon(new ImageIcon(img));
                    try{
                        Thread.sleep(100);
                    } catch (InterruptedException ex){
                        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex){
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            while(window == 2){
                while(run){
                    if(this.getRandom() == 1){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img1.jpg")).getImage();
                    }else if (this.getRandom() == 2){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img2.jpg")).getImage();
                    }else{
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img3.jpg")).getImage();
                    }
                    img = img.getScaledInstance(315, 400, java.awt.Image.SCALE_SMOOTH);
                    jLabel3.setIcon(new ImageIcon(img));
                    try{
                        Thread.sleep(100);
                    } catch (InterruptedException ex){
                        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex){
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            while(window == 3){
                while(run){
                    if(this.getRandom() == 1){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img1.jpg")).getImage();
                    }else if (this.getRandom() == 2){
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img2.jpg")).getImage();
                    }else{
                        img = new ImageIcon(this.getClass().getResource("/Imagenes/img3.jpg")).getImage();
                    }
                    img = img.getScaledInstance(315, 400, java.awt.Image.SCALE_SMOOTH);
                    jLabel4.setIcon(new ImageIcon(img));
                    try{
                        Thread.sleep(100);
                    } catch (InterruptedException ex){
                        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try{
                    Thread.sleep(100);
                } catch (InterruptedException ex){
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
                
                            

        
    }
}
